/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex.raw('TRUNCATE TABLE equipment_table RESTART IDENTITY CASCADE');

  // Retrieve deployment IDs from `deployments_table`
  const deployments = await knex('deployments_table')
    .whereIn('name', [
      'Operation Rift Sentinel',
      'Operation Titan’s Descent',
      'Operation Phantom Veil',
      'Operation Void Genesis',
      'Operation Eclipse Watch',
      'Operation Chrono Storm',
      'Operation Abyss Walker',
      'Operation Nexus Breaker',
      'Operation Celestial Beacon',
      'Operation Paradox Rift',
      'Operation Silent Horizon',
      'Operation Obsidian Ghost',
      'Operation Null Horizon',
      'Operation Solar Fury',
      'Operation Iron Dawn',
      'Operation Dark Matter',
      'Operation Steel Rain',
      'Operation Quantum Shadow',
      'Operation Starfall',
      'Operation Night Harvest',
      'Operation Mindfire',
      'Operation Sky Breaker',
      'Operation Thunder Strike',
      'Operation Frost Forge',
      'Operation Angel’s Wrath',
      'Operation Event Horizon',
      'Operation Guardian Protocol',
      'Operation Storm Front',
      'Operation Inferno Reach',
      'Operation Moonfall',
      'Operation Last Light',
      'Operation Dawn Piercer',
      'Operation Ghost Orbit',
      'Operation Blood Moon',
      'Operation Mirage Strike',
      'Operation Silent Blade',
      'Operation Lightning Spear',
      'Operation Winter Claw',
      'Operation Ghost Step',
      'Operation Mind Fracture',
      'Operation Dead Echo',
      'Operation Data Plague',
      'Operation Blackout',
      'Operation Event Collapse',
      'Operation Flesh War',
      'Operation Time Cut',
      'Operation Rust Tide',
      'Operation Final Whisper',
      'Operation Iron Descent',
      'Operation Apocalypse Key',
      'Operation Scorched Earth',
      'Operation Shatterpoint',
      'Operation Sunburst',
      'Operation Lifeline',
      'Operation Silent Wire',
      'Operation Frozen Heart',
      'Operation Phase Leap',
      'Operation Iron Mender'
    ]);

  // Create a mapping of deployment names to IDs
  const deploymentMap = deployments.reduce((acc, deployment) => {
    acc[deployment.name] = deployment.id;
    return acc;
  }, {});

  // Insert equipment data
  await knex('equipment_table').insert([
    {name: 'M1A2 Dimensional Rift Gateway', id_deployments: deploymentMap['Operation Rift Sentinel'], status: 'Fully Operational' },
    {name: 'Aether-Forged Combat Suit', id_deployments: deploymentMap['Operation Titan’s Descent'], status: 'Experimental Testing' },
    {name: 'Echo-Phase Tactical Comms', id_deployments: deploymentMap['Operation Phantom Veil'], status: 'Field Ready' },
    {name: 'Oblivion-Class Void Rifle', id_deployments: deploymentMap['Operation Void Genesis'], status: 'Restricted Access' },
    {name: 'Singularity Breach Charge', id_deployments: deploymentMap['Operation Eclipse Watch'], status: 'Armed & Ready' },
    {name: 'Chrono Stabilizer Beacon', id_deployments: deploymentMap['Operation Chrono Storm'], status: 'Active Monitoring' },
    {name: 'Shadow Dagger Mk-VII', id_deployments: deploymentMap['Operation Abyss Walker'], status: 'Prototype' },
    {name: 'Nexus-Linked Field Generator', id_deployments: deploymentMap['Operation Nexus Breaker'], status: 'Online' },
    {name: 'Celestial Navigation Core', id_deployments: deploymentMap['Operation Celestial Beacon'], status: 'Operational' },
    {name: 'Quantum Disruption Array', id_deployments: deploymentMap['Operation Paradox Rift'], status: 'Under Maintenance' },
    {name: 'Silent Horizon Recon Drone', id_deployments: deploymentMap['Operation Silent Horizon'], status: 'Deployed' },
    {name: 'Obsidian Ghost Cloaking Module', id_deployments: deploymentMap['Operation Obsidian Ghost'], status: 'Testing Phase' },
    {name: 'Night Wing', id_deployments: deploymentMap['Operation Null Horizon'], status: 'Testing Phase' },
    {name: 'Helix-Pattern Plasma Carbine', id_deployments: deploymentMap['Operation Solar Fury'], status: 'Combat Ready'},
    {name: 'Graviton Pulse Gauntlets', id_deployments: deploymentMap['Operation Iron Dawn'], status: 'Calibration Phase'},
    {name: 'Stellaris Void Anchor', id_deployments: deploymentMap['Operation Dark Matter'], status: 'Critical Failure'},
    {name: 'Titanium-Shell Combat Drone', id_deployments: deploymentMap['Operation Steel Rain'], status: 'Standby'},
    {name: 'Quantum Entanglement Sidearm', id_deployments: deploymentMap['Operation Quantum Shadow'], status: 'Restricted Access'},
    {name: 'Nebula Shroud Field', id_deployments: deploymentMap['Operation Starfall'], status: 'Active Deployment'},
    {name: 'Photon Edge Vibroblade', id_deployments: deploymentMap['Operation Night Harvest'], status: 'Awaiting Orders'},
    {name: 'Eclipse-Type Neural Interface', id_deployments: deploymentMap['Operation Mindfire'], status: 'Testing Phase'},
    {name: 'Astral Projection Harness', id_deployments: deploymentMap['Operation Sky Breaker'], status: 'Prototype'},
    {name: 'Hyperion-Class Railgun', id_deployments: deploymentMap['Operation Thunder Strike'], status: 'Armed & Ready'},
    {name: 'Zero-Point Energy Core', id_deployments: deploymentMap['Operation Frost Forge'], status: 'In Storage'},
    {name: 'Seraphim Wing Exo-Suit', id_deployments: deploymentMap['Operation Angel’s Wrath'], status: 'Operational'},
    {name: 'Dark Matter Reactor', id_deployments: deploymentMap['Operation Event Horizon'], status: 'Under Maintenance'},
    {name: 'Sentinel AI Combat Module', id_deployments: deploymentMap['Operation Guardian Protocol'], status: 'Online'},
    {name: 'Vortex Shield Emitter', id_deployments: deploymentMap['Operation Storm Front'], status: 'Experimental Testing'},
    {name: 'Hades-Type Incendiary Launcher', id_deployments: deploymentMap['Operation Inferno Reach'], status: 'Decommissioned'},
    {name: 'Lunar Forge Nanite Swarm', id_deployments: deploymentMap['Operation Moonfall'], status: 'Unstable'},
    {name: 'Pandora’s Cache Tactical Nuke', id_deployments: deploymentMap['Operation Last Light'], status: 'Locked'},
    {name: 'Solaris Beam Array', id_deployments: deploymentMap['Operation Dawn Piercer'], status: 'Overheating'},
    {name: 'Wraith-Stealth Orbital Satellite', id_deployments: deploymentMap['Operation Ghost Orbit'], status: 'Silent Running'},
    {name: 'Neon Reaper Particle Cannon', id_deployments: deploymentMap['Operation Blood Moon'], status: 'Overclocked'},
    {name: 'Blackstar Tactical Hologram', id_deployments: deploymentMap['Operation Mirage Strike'], status: 'Active Decoy'},
    {name: 'Voidrend Combat Knife', id_deployments: deploymentMap['Operation Silent Blade'], status: 'Lethal'},
    {name: 'Stormbringer Electro-Rail', id_deployments: deploymentMap['Operation Lightning Spear'], status: 'Charging'},
    {name: 'Frostbite Cryo-Grenade', id_deployments: deploymentMap['Operation Winter Claw'], status: 'Frozen Stock'},
    {name: 'Phantom Veil Cloaking Rig', id_deployments: deploymentMap['Operation Ghost Step'], status: 'Active Camouflage'},
    {name: 'Neural Scrambler Pod', id_deployments: deploymentMap['Operation Mind Fracture'], status: 'Illegal'},
    {name: 'Specter ECHO Drone', id_deployments: deploymentMap['Operation Dead Echo'], status: 'MIA'},
    {name: 'Hackwire Virus Injector', id_deployments: deploymentMap['Operation Data Plague'], status: 'Corrupting'},
    {name: 'Nightshade EMP Blade', id_deployments: deploymentMap['Operation Blackout'], status: 'Disruptive'},
    {name: 'Singularity Grenade', id_deployments: deploymentMap['Operation Event Collapse'], status: 'Forbidden'},
    {name: 'Biosynth Combat Symbiote', id_deployments: deploymentMap['Operation Flesh War'], status: 'Mutating'},
    {name: 'Chronoskip Jump Boots', id_deployments: deploymentMap['Operation Time Cut'], status: 'Unstable'},
    {name: 'Plagueborn Nanite Cloud', id_deployments: deploymentMap['Operation Rust Tide'], status: 'Contained'},
    {name: 'Doomsday Frequency Beacon', id_deployments: deploymentMap['Operation Final Whisper'], status: 'Dormant'},
    {name: 'Titanfall Siege Mech', id_deployments: deploymentMap['Operation Iron Descent'], status: 'Standing By'},
    {name: 'Oblivion Warhead', id_deployments: deploymentMap['Operation Apocalypse Key'], status: 'Locked'},
    {name: 'Hellfire Plasma Mortar', id_deployments: deploymentMap['Operation Scorched Earth'], status: 'Ready to Fire'},
    {name: 'Gravity Hammer', id_deployments: deploymentMap['Operation Shatterpoint'], status: 'Awaiting Clearance'},
    {name: 'Solar Flare Artillery', id_deployments: deploymentMap['Operation Sunburst'], status: 'Aiming'},
    {name: 'Medi-Gel Rapid Healer', id_deployments: deploymentMap['Operation Lifeline'], status: 'Sterilized'},
    {name: 'Omni-Tool Hacking Kit', id_deployments: deploymentMap['Operation Silent Wire'], status: 'Connected'},
    {name: 'Stasis Field Generator', id_deployments: deploymentMap['Operation Frozen Heart'], status: 'Active'},
    {name: 'Warp Jump Pack', id_deployments: deploymentMap['Operation Phase Leap'], status: 'Calibrating'},
    {name: 'Sentinel Repair Nanobots', id_deployments: deploymentMap['Operation Iron Mender'], status: 'Patching'},
  ]);
};
